### ISSUE TITLE
race condition and crash process

### ISSUE THREAD

**Issue by JokerCatz** [isamu/rocksdb-ruby#15]
just demo code ...

    require "rocksdb"
    key = "test"
    value = "1"
    rocksdb = RocksDB::DB.new "/tmp/file"
    rocksdb2 = RocksDB::DB.new "/tmp/file"
    rocksdb.put(key, value)
    rocksdb2.put(key, value)
    # ruby kernel exception

did here need add lock check or something like mutex to skip this condition ?

**Comment by isamu** [comment]
I changed that raise RocksDB::DBError when same file open twice.
I alse added singleton method.

**Comment by JokerCatz** [comment]
`RocksDB::DBError: error /tmp/file alread open`

it looking good , but I'll wait version change and use it to my project , many thanx , this gem is very useful for fast local DB :)
