### ISSUE TITLE
does not compile on freebsd

### ISSUE THREAD

**Issue by devosalain** [isamu/rocksdb-ruby#19]
Header files are in :
 /usr/local/include/rocksdb

Maybe I must provide a configuration option ?

**Comment by isamu** [comment]
Thank you for your feedback.

I have no FreeBSD env.
Could you try to update https://github.com/isamu/rocksdb-ruby/blob/master/ext/rocksdb/extconf.rb ?

**Comment by isopen** [comment]
You can try to install rocksdb.
In Debian, it works like this: `sudo apt-get install librocksdb-dev`
In freebsd you can try building from `source` or find `port`.
