### ISSUE TITLE
RocksDB#exists? produces false-positives

### ISSUE THREAD

**Issue by daniel-ferguson** [isamu/rocksdb-ruby#23]
`RocksDB#exists?` naming suggests to me that it returns `true` when the key exists and `false` when the key does not exist. This assumption is present in the README too:

> You can check, if key exists:
>
>     rocksdb.exists? "Real Key"
>     # => true
>     
>     rocksdb.exists? "Imaginary Key"
>     # => false

In running some code which relies on checking the existence of keys in a few million key database I saw some strange behaviour. It turned out `#exists?` was returning `true` in some cases where the key did not exist in the database (confirmed using `#get`).

Looking at the implementation for `#exists?` shows it calls `KeyMayExist` from the rocksdb codebase <https://github.com/isamu/rocksdb-ruby/blob/2a4a621fa0d5277761bd6e56aa3c037a68260934/ext/rocksdb/rocksdb_db_rb.cc#L225-L232>

`KeyMayExist` in the rocksdb codebase (https://github.com/facebook/rocksdb/blob/689b13e6396011317db4f04a88e72323aead32bd/include/rocksdb/db.h#L646-L662) is documented with:

>    // If the key definitely does not exist in the database, then this method
>    // returns false, else true. If the caller wants to obtain value when the key
>    // is found in memory, a bool for 'value_found' must be passed. 'value_found'
>    // will be true on return if value has been set properly.
>    // This check is potentially lighter-weight than invoking DB::Get(). One way
>    // to make this lighter weight is to avoid doing any IOs.
>    // Default implementation here returns true and sets 'value_found' to false

---

Would it be possible to make this behaviour a little less surprising, either with documentation or a slight rename of the method?

**Comment by Nakilon** [comment]
I'm not familiar with a plenty of DB interfaces but I imagine adding the method `definitely_exists?` and a note about false positives in `exists?` method doc.

**Comment by katafrakt** [comment]
I'd vote for only improving the docs. `exists?` is a possibly faster way to check if the key exists that doing `get` and checking that the returned value is not `nil`. So, if you need to be sure, you have a way to check it. No need to create `definitely_exists?` (which would have to do `get` anyway probably) or parameterize `exists?`.

**Comment by isamu** [comment]
Thank you everyone.

I updated the document.
https://github.com/isamu/rocksdb-ruby/commit/e8843116209ca548646853acae4d6851c9685626
If you need other `exists?` method, would you like to create a new PR.

Thanks.
