### ISSUE TITLE
Iterator with each method?

### ISSUE THREAD

**Issue by maasha** [isamu/rocksdb-ruby#6]
How about this:

````
#Iteration
iterator = rocksdb.new_iterator

iterator.seek_to_first
while(iterator.valid)
  iterator.value
  iterator.key
  iterator.next
end
iterator.close
````
as a nice ruby each method? ala:

````
rocksdb.each do |key, value|
end
````

**Comment by isamu** [comment]
add each_index and each_with_index.

In you case , use 

    rocksdb.each_with_index do |key, value|
    end

**Comment by maasha** [comment]
The Ruby way would be to have an each method - and then include the Enumerable module to get free each_with_index method and others.

**Comment by isamu** [comment]
class RocksDBEnumerable
   include Enumerable
 
   def initialize(*args)
     @rocksdb = RocksDB::DB.new(*args)
   end
 
   def each(&block)
     @rocksdb.each do |member|
       block.call(member)
     end
   end
 end
 
 db = RocksDBEnumerable.new("/tmp/file")
 db.map(&:downcase)
 db.each_slice(2){|data| p data }

**Comment by maasha** [comment]
Yes, that is very elegant. I think it should be included natively in rocksdb-ruby :o)

**Comment by isamu** [comment]
each method supported ruby's Enumerable.

**Comment by maasha** [comment]
Basically the Iteration section from the Usage in the README file is not Ruby-ish and I suggest it should be updated.

**Comment by isamu** [comment]
Closed this ticket as fixed each method problem.
I will modify README.
